# devglow
# Theme create by: https://github.com/phatnt199
# Update by(sort by time):

# Thank you!
code_syntax_highlight = "devglow"

# ========= Border =========
file_panel_border = "#383838"
sidebar_border = "#383838"
footer_border = "#383838"

# ========= Border Active =========
file_panel_border_active = "#EBC17A"
sidebar_border_active = "#AF5F5F"
footer_border_active = "#87AFAF"
modal_border_active = "#87AFAF"

# ========= Background (bg) =========
full_screen_bg = "#080808"
file_panel_bg = "#080808"
sidebar_bg = "#080808"
footer_bg = "#111111"
modal_bg = "#080808"

# ========= Foreground (fg) =========
full_screen_fg = "#EEE2DE"
file_panel_fg = "#EEE2DE"
sidebar_fg = "#EEE2DE"
footer_fg = "#797979"
modal_fg = "#EEE2DE"

# ========= Special Color =========
cursor = "#EBC17A"
correct = "#7DB9B6"
error = "#EA5455"
hint = "#7EAAC7"
cancel = "#924653"
# Gradient color can only have two colors!
gradient_color = ["#EBC17A", "#7DB9B6"]

# ========= File Panel Special Items =========
file_panel_top_directory_icon = "#AF875F"
file_panel_top_path = "#AF5F5F"
file_panel_item_selected_fg = "#7EAAC7"
file_panel_item_selected_bg = "#282828"

# ========= Sidebar Special Items =========
sidebar_title = "#AF875F"
sidebar_item_selected_fg = "#D59572"
sidebar_item_selected_bg = "#282828"
sidebar_divider = "#383838"

# ========= Modal Special Items =========
modal_cancel_fg = "#080808"
modal_cancel_bg = "#924653"

modal_confirm_fg = "#080808"
modal_confirm_bg = "#7EAAC7"

# ========= Help Menu =========
help_menu_hotkey = "#7EAAC7"
help_menu_title = "#924653"
